INSERT INTO `indicadores` (`id`, `agente`, `tipo`, `id_objetivo`, `frecuencia`, `nombre`) VALUES
('Air-e.1.1.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'Ejecución de inversiones orientadas a la calidad del servicio aprobadas en el plan de inversión.'),
('Air-e.1.2.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'Cumplimiento del programa de mantenimientos por circuito.'),
('Air-e.1.3.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'Mejora SAIDI por circuito.'),
('Air-e.1.4.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'Mejora de SAIFI por circuito.'),
('Air-e.1.5.a.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'cobertura en medios de comunicación masivos.'),
('Air-e.1.5.b.P', 'Air-e', 'Parcial', 'Air-e.1', 1, 'Notificación a través de mensajes de texto y/o correo electrónico y/o cartas a los usuarios industriales.'),
('Air-e.1.6.a.P', 'Air-e', 'Parcial', 'Air-e.1', 2, 'Mejora en el desempeńo del indicador de calidad individual DIU.'),
('Air-e.1.6.b.P', 'Air-e', 'Parcial', 'Air-e.1', 2, 'Mejora en el desempeńo del indicador de calidad individual FIU.'),
('Air-e.2.1.P', 'Air-e', 'Parcial', 'Air-e.2', 1, 'Ejecución de inversiones orientadas a la  calidad del servicio en el STR aprobadas en el plan de inversión'),
('Air-e.2.2.P', 'Air-e', 'Parcial', 'Air-e.2', 1, 'Cumplimiento del programa de mantenimientos por activo'),
('Air-e.3.1.P', 'Air-e', 'Parcial', 'Air-e.3', 1, 'Ejecución de inversiones aprobadas en el plan de inversión orientadas a la calidad de la potencia en los activos de nivel de tensión 4, 3 y 2.'),
('Air-e.4.1.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de inversiones orientadas a recuperación de pérdidas en el CONPES 3910/17 y CONPES 3933/18'),
('Air-e.4.2.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de proyectos de instalación de medida centralizada en los grandes consumidores incluidos en el plan de reducción de pérdidas'),
('Air-e.4.3.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de proyectos de aseguramiento de red incluidos en el plan de reducción de inversiones '),
('Air-e.4.4.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de proyectos de instalación de medición para usuarios sin medidor y aseguramiento de la medida incluidos en el plan de reducción de pérdidas'),
('Air-e.4.5.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de campańas de normalización para clientes masivos  (3,4,5 y 6, comercial, industrial regulados) incluidas en el plan de reducción de pérdidas'),
('Air-e.4.6.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de proyectos de instalación de macro medición incluidas en el plan de reducción de inversiones'),
('Air-e.4.7.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de inversión en gestión social incluida en el plan de reducción de pérdidas'),
('Air-e.4.8.P', 'Air-e', 'Parcial', 'Air-e.4', 1, 'Ejecución de proyectos de normalización de la medición (totalizadores) en barrios subnormales'),
('Air-e.5.1.P', 'Air-e', 'Parcial', 'Air-e.5', 1, 'Construir e implementar un plan de gestión de riesgo eléctrico de acuerdo con los artículos 26 y 27 del Reglamento Técnico de Instalaciones Eléctricas (RETIE).'),
('Air-e.6.1.P', 'Air-e', 'Parcial', 'Air-e.6', 1, 'Implementar una estrategia que optimice el procedimiento de trámite oportuno y de calidad de reclamaciones por parte de la empresa'),
('Air-e.6.2.P', 'Air-e', 'Parcial', 'Air-e.6', 1, 'Efectuar seguimiento a la herramienta para solicitar turnos en línea para las oficinas de atención al cliente.'),
('Air-e.6.3.P', 'Air-e', 'Parcial', 'Air-e.6', 0, 'Implementar una estrategia para aumentar la dispersión de recepción de PQR´s entre los diferentes canales de atención medida por desviación estándar. (Eliminado)'),
('Air-e.7.1.P', 'Air-e', 'Parcial', 'Air-e.7', 1, 'Proyecto de identificación y caracterización de las condiciones de la Empresa y de los usuarios de su mercado.'),
('Air-e.7.2.P', 'Air-e', 'Parcial', 'Air-e.7', 1, 'Construir e implementar un programa de RSE acorde a las necesidades identificadas en el primer indicador.'),
('Air-e.8.1.P', 'Air-e', 'Parcial', 'Air-e.8', 1, 'Diseńar y estructurar un programa de gestión social para la intervención de Barrios Subnormales (BSN), que permitan un mayor acercamiento y acompańamiento a los usuarios potenciales de las campańas de normalización, con el fin de lograr la sensibilización y aceptación que se requiere.'),
('Air-e.8.2.P', 'Air-e', 'Parcial', 'Air-e.8', 1, 'Diseńar y estructurar un programa de gestión social para intervención en las Zonas de Difícil Gestión (ZDG), que permitan un mayor acercamiento y acompańamiento con la comunidad y mejorar los índices de recaudo de estas áreas especiales.'),
('Air-e.1.1.a.R', 'Air-e', 'Resultado', 'Air-e.1', 3, 'Mejorar la continuidad del servicio en cuanto a la duración de las interrupciones en su mercado de comercialización.'),
('Air-e.1.1.b.R', 'Air-e', 'Resultado', 'Air-e.1', 2, 'Mejorar la continuidad del servicio en cuanto a la duración de las interrupciones no programadas en su mercado de comercialización.'),
('Air-e.1.2.a.R', 'Air-e', 'Resultado', 'Air-e.1', 3, 'Mejorar la continuidad del servicio en cuanto a la frecuencia de las interrupciones en su mercado de comercialización.'),
('Air-e.1.2.b.R', 'Air-e', 'Resultado', 'Air-e.1', 2, 'Mejorar la continuidad del servicio en cuanto a la frecuencia de las interrupciones no programadas en su mercado de comercialización.'),
('Air-e.1.3.R', 'Air-e', 'Resultado', 'Air-e.1', 1, 'Informar a los usuarios las interrupciones programadas.'),
('Air-e.2.1.R', 'Air-e', 'Resultado', 'Air-e.2', 3, 'Reducir la demanda no atendida no programada en todo el mercado de comercialización a nivel de STR. '),
('Air-e.2.2.a.R', 'Air-e', 'Resultado', 'Air-e.2', 3, 'Reducir las horas de indisponibilidad en los activos del STR:\n2a). Indisponibilidad Activos asociadas a interrupciones no programados en activos del STR en el ańo t.'),
('Air-e.2.2.b.R', 'Air-e', 'Resultado', 'Air-e.2', 3, 'Indisponibilidad Activos asociadas a interrupciones programados en activos del STR en el ańo t.'),
('Air-e.2.3.a.R', 'Air-e', 'Resultado', 'Air-e.2', 1, 'Gestión para la Reducción de Indisponibilidad de Activos operados por terceros en el mercado del operador.\n3a) Ajuste a los contratos de conexión de Activos representados de terceros en el STR.'),
('Air-e.2.3.b.R', 'Air-e', 'Resultado', 'Air-e.2', 1, 'Aplicación del Protocolo de Consignaciones en el STR.'),
('Air-e.3.1.R', 'Air-e', 'Resultado', 'Air-e.3', 3, 'Infraestructura para cumplimiento de la CREG 024 de 2005.'),
('Air-e.3.2.R', 'Air-e', 'Resultado', 'Air-e.3', 3, 'Mantener los niveles de tensión dentro de los estándares regulatorios para valores de Desviaciones estacionarias de Tensión.'),
('Air-e.3.3.R', 'Air-e', 'Resultado', 'Air-e.3', 3, 'Mantener la distorsión armónica dentro de los estándares regulatorios (THDV).'),
('Air-e.4.1.R', 'Air-e', 'Resultado', 'Air-e.4', 3, 'Reducir el índice de pérdidas'),
('Air-e.4.2.R', 'Air-e', 'Resultado', 'Air-e.4', 3, 'Reducir el numero de usuarios sin medidor en el mercado de comercialización'),
('Air-e.5.1.R', 'Air-e', 'Resultado', 'Air-e.5', 3, 'Disminuir del número de accidentes de origen eléctrico en el sistema eléctrico del operador'),
('Air-e.5.2.R', 'Air-e', 'Resultado', 'Air-e.5', 1, 'Ejecución de inversiones orientadas a la sustitución de red monohilo aprobadas en el plan de inversión'),
('Air-e.6.1.R', 'Air-e', 'Resultado', 'Air-e.6', 3, 'Reducir el número de fallos sancionatorios por Silencio Administrativo Positivo (SAP) en contra de la empresa recibidas por la SSPD.'),
('Air-e.6.2.R', 'Air-e', 'Resultado', 'Air-e.6', 3, 'Mejorar la calidad de las decisiones de los Recursos De Reposición.    '),
('Air-e.6.3.R', 'Air-e', 'Resultado', 'Air-e.6', 1, 'Aumentar la cantidad de PQRs no presenciales'),
('Air-e.7.1.R', 'Air-e', 'Resultado', 'Air-e.7', 3, 'Aumento del sentido de pertenencia de colaboradores.'),
('Air-e.7.2.R', 'Air-e', 'Resultado', 'Air-e.7', 3, 'Mejora de la imagen ante los usuarios '),
('Air-e.8.1.R', 'Air-e', 'Resultado', 'Air-e.8', 3, 'Participar en todas las convocatorias PRONE, establecidas por el MME a lo largo de las diferentes vigencias.'),
('Air-e.8.2.R', 'Air-e', 'Resultado', 'Air-e.8', 3, 'Mejorar el índice de proyectos de normalización finalizados.'),
('Air-e.8.3.R', 'Air-e', 'Resultado', 'Air-e.8', 3, 'Disminución del número de clientes en Barrios Subnormales dentro del mercado de comercialización'),
('Air-e.8.4.R', 'Air-e', 'Resultado', 'Air-e.8', 3, 'Mejorar los índices de morosidad de las ZDG'),
('Air-e.9.1.R', 'Air-e', 'Resultado', 'Air-e.9', 1, 'Clientes  verificados en cuánto al Vínculo Cliente - Transformador'),
('Air-e.9.2.R', 'Air-e', 'Resultado', 'Air-e.9', 2, 'Normalización de las Fronteras de Distribución.'),
('Afinia.1.1.P', 'Afinia', 'Parcial', 'Afinia.1', 1, 'Ejecución de inversiones orientadas a la calidad del servicio aprobadas en el plan de inversión'),
('Afinia.1.2.P', 'Afinia', 'Parcial', 'Afinia.1', 1, 'Cumplimiento del programa de mantenimientos por circuito'),
('Afinia.1.3.P', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Mejora SAIDI por circuito'),
('Afinia.1.4.P', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Mejora de SAIFI por circuito'),
('Afinia.1.5.P', 'Afinia', 'Parcial', 'Afinia.1', 1, 'Reducir los tiempos de atención de interrupciones no programadas los usuarios del mercado Caribe Mar'),
('Afinia.1.6.a.P', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Avisos de las interrupciones programadas de conformidad con la resolución CREG 015 de 2018:  Cobertura en medios de comunicación masivos'),
('Afinia.1.6.b.P', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Avisos de las interrupciones programadas de conformidad con la resolución CREG 015 de 2018: Notificación a través de mensajes de texto y/o correo electrónico y/o cartas a los usuarios industriales'),
('Afinia.2.1.P', 'Afinia', 'Parcial', 'Afinia.2', 1, 'Ejecución de inversiones orientadas a la  calidad del servicio en el STR aprobadas en el plan de inversión\n'),
('Afinia.2.2.P', 'Afinia', 'Parcial', 'Afinia.2', 1, 'Cumplimiento del programa de mantenimientos por activo'),
('Afinia.3.1.P', 'Afinia', 'Parcial', 'Afinia.3', 1, 'Ejecución de inversiones aprobadas en el plan de inversión orientadas a la calidad de la potencia en los activos de nivel de tensión 4, 3 y 2.'),
('Afinia.4.1.P', 'Afinia', 'Parcial', 'Afinia.4', 1, 'Ejecución de Inversiones orientadas a recuperación de pérdidas del documento CONPES 3966 de 2019'),
('Afinia.4.2.P', 'Afinia', 'Parcial', 'Afinia.4', 1, 'Ejecución Plan de Control de Pérdidas de Energía: incluye las actividades de: \na) Campańas sistemáticas en consumidores regulados y medios\nb) Gestión de grandes consumidores\nc) Instalación de Macromedida'),
('Afinia.4.3.P', 'Afinia', 'Parcial', 'Afinia.4', 1, 'Ejecución Plan de Reducción de Pérdidas de Energía: incluye las actividades de:\na) Instalación de medidores a usuarios sin medición\nb)Sistema de medición centralizada AMI \nc) Aseguramiento de la red'),
('Afinia.4.4.P', 'Afinia', 'Parcial', 'Afinia.4', 1, 'Ejecución plan de inversiones activos de uso dirigido a gestión de perdidas'),
('Afinia.5.1.P', 'Afinia', 'Parcial', 'Afinia.5', 1, 'Construir e implementar un plan de gestión de riesgo eléctrico de acuerdo con los artículos 26 y 27 del Reglamento Técnico de Instalaciones Eléctricas (RETIE).'),
('Afinia.6.1.P', 'Afinia', 'Parcial', 'Afinia.6', 1, 'Implementar una estrategia que optimice el procedimiento de trámite oportuno y de calidad de reclamaciones por parte de la empresa'),
('Afinia.6.2.P', 'Afinia', 'Parcial', 'Afinia.6', 1, 'Mantener el porcentaje de casos resueltos mediante el programa de atención al cliente en primer contacto del universo de casos que aplique.'),
('Afinia.7.1.P', 'Afinia', 'Parcial', 'Afinia.7', 1, 'Construir y establecer la línea base del RSE.  '),
('Afinia.7.2.P', 'Afinia', 'Parcial', 'Afinia.7', 1, 'Cumplimiento a las acciones definidas en el plan de mejoras en el ańo analizado.'),
('Afinia.8.1.P', 'Afinia', 'Parcial', 'Afinia.8', 1, 'Diseńar e implementar un programa de acompańamiento social para la implementación de los programas de pérdidas, normalización de subnormales y prepago, identificando aquellas acciones con foco en ZDG y BSN'),
('Afinia.1.1.a.R', 'Afinia', 'Parcial', 'Afinia.1', 3, 'Mejorar la continuidad del servicio en cuanto a la duración de las interrupciones  programadas y no programadas según la metodología definida en la Resolución CREG 015 de 2018 '),
('Afinia.1.1.b.R', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Mejorar la continuidad del servicio en cuanto a la duración de las interrupciones no programadas'),
('Afinia.1.2.a.R', 'Afinia', 'Parcial', 'Afinia.1', 3, 'Mejorar la continuidad del servicio en cuanto a la frecuencia de las interrupciones programadas y no programadas según la metodología definida en la Resolución CREG 015 de 2018'),
('Afinia.1.2.b.R', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Mejorar la continuidad del servicio en cuanto a la frecuencia de las interrupciones no programadas'),
('Afinia.1.3.R', 'Afinia', 'Parcial', 'Afinia.1', 2, 'Informar a los usuarios las interrupciones programadas'),
('Afinia.2.1.R', 'Afinia', 'Parcial', 'Afinia.2', 3, 'Reducir la demanda no atendida no programada en todo el mercado de comercialización a nivel de STR'),
('Afinia.2.2.a.R', 'Afinia', 'Parcial', 'Afinia.2', 3, 'Indisponibilidad Activos asociadas a interrupciones no programados en activos del STR en el ańo t.'),
('Afinia.2.2.b.R', 'Afinia', 'Parcial', 'Afinia.2', 3, 'Indisponibilidad Activos asociadas a interrupciones programados en activos del STR en el ańo t.'),
('Afinia.3.1.R', 'Afinia', 'Parcial', 'Afinia.3', 3, 'Instalar el sistema de medición y registro de calidad de la Potencia en el 100% de las barras de las subestaciones de Niveles de Tensión 4, 3 y 2, así como en el 5 % de los circuitos a 13.2 kV en cumplimiento de la Resolución CREG 024 de 2005'),
('Afinia.3.2.R', 'Afinia', 'Parcial', 'Afinia.3', 3, 'Mantener los niveles de tensión dentro de los estándares regulatorios para valores de Desviaciones estacionarias de Tensión e Interrupciones Transitorias'),
('Afinia.3.3.R', 'Afinia', 'Parcial', 'Afinia.3', 3, 'Mantener la distorsión armónica dentro de los estándares regulatorios.'),
('Afinia.4.1.R', 'Afinia', 'Parcial', 'Afinia.4', 3, 'Reducir el índice de pérdidas'),
('Afinia.4.2.R', 'Afinia', 'Parcial', 'Afinia.4', 3, 'Reducir el numero de usuarios sin medidor en el mercado de comercialización'),
('Afinia.5.1.R', 'Afinia', 'Parcial', 'Afinia.5', 3, 'Disminuir del número de accidentes de origen eléctrico en el sistema eléctrico del operador'),
('Afinia.5.2.R', 'Afinia', 'Parcial', 'Afinia.5', 1, 'Ejecución de inversiones orientadas a la sustitución de red monohilo aprobadas en el plan de inversión'),
('Afinia.6.1.R', 'Afinia', 'Parcial', 'Afinia.6', 3, 'Reducir el número de sanciones por Silencio Administrativo Positivo (SAP) aplicadas por la SSPD.'),
('Afinia.6.2.R', 'Afinia', 'Parcial', 'Afinia.6', 3, 'Mejorar la calidad de las decisiones de los Recursos de Reposición '),
('Afinia.7.1.R', 'Afinia', 'Parcial', 'Afinia.7', 3, 'Aumento del sentido de pertenencia de colaboradores.'),
('Afinia.7.2.R', 'Afinia', 'Parcial', 'Afinia.7', 3, 'Mejora de la imagen ante los usuarios '),
('Afinia.8.1.R', 'Afinia', 'Parcial', 'Afinia.8', 3, 'Disminución del número de Clientes en Barrios Subnormales'),
('Afinia.8.2.R', 'Afinia', 'Parcial', 'Afinia.8', 3, 'Implementación de sistema de medición prepago'),
('Afinia.8.3.R', 'Afinia', 'Parcial', 'Afinia.8', 3, 'Reducción de cartera');