INSERT INTO `variables` (`id`, `id_indicador`, `variable`, `descripcion`) VALUES
(1, 'Air-e.1.1.P', 'VUC_Ejecutadot', 'Valor de las unidades constructivas instaladas durante cada uno de los trimestres de evaluación y acumulado según curva S, valoradas según listado de UC del capítulo 14 de la resolución CREG 015 de 2018. Programado: Inversión total programada hasta el trimestre que se evalúa'),
(2, 'Air-e.1.1.P', 'VUC_Programadot', 'Valor de las unidades constructivas programadas a intervenir durante cada uno de los trimestres de evaluación y acumulado según curva S, valoradas según listado de UC del capítulo 14 de la resolución CREG 015 de 2018.'),
(3, 'Air-e.1.2.P', 'Ejecución Real t', 'Actividades ejecutadas en labores de mantenimiento: Podas, Balanceo, Termografía y Lavado.'),
(4, 'Air-e.1.2.P', 'Ejecución Programada t', 'Actividades programadas en labores de mantenimiento: Podas, Balanceo, Termografías y Lavado.'),
(5, 'Air-e.1.2.P', '%Pond t', 'Porcentaje de ponderación asignado por el OR, para cada actividad de mantenimiento: Podas, Balanceo, Termografías y Lavado.'),
(6, 'Air-e.1.3.P', 'SAIDICM_T', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones programadas y no programadas (META)'),
(7, 'Air-e.1.3.P', 'SAIDIC_T', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones ocurridas programadas y no programadas'),
(8, 'Air-e.1.4.P', 'SAIFICM_T', 'Frecuencia (cantidad total de los eventos que en promedio) perciben los usuarios en el circuito evaluado del SDL, incluye interrupciones programadas y no programadas (META).'),
(9, 'Air-e.1.4.P', 'SAIFIC_T', 'Frecuencia (cantidad total de los eventos que en promedio) perciben los usuarios en el circuito evaluado del SDL, incluye interrupciones ocurridas programadas y no programadas. '),
(10, 'Air-e.1.5.a.P', 'MunicipiosCubiertos', 'Municipios cubiertos por medios de comunicación'),
(11, 'Air-e.1.5.a.P', 'TotalMunicipiosAtendidos', 'Municipios atendidos por el operador de red.'),
(12, 'Air-e.1.5.b.P', 'UsuariosInfMedio', 'Usuarios informados con medio de comunicación.'),
(13, 'Air-e.1.5.b.P', 'TotalUsuariosConMedio', 'Total Usuarios con medio de comunicación.'),
(14, 'Air-e.1.6.a.P', 'NU_mDIUs', 'Número usuarios DIU'),
(15, 'Air-e.1.6.b.P', 'NU_mFIUs', 'Número usuarios FIU'),
(16, 'Air-e.2.1.P', 'VUC_ejecutado t', 'valor de las unidades constructivas instaladas en el trimestre de evaluación y acumulado según la curva S.'),
(17, 'Air-e.2.1.P', 'VUC_programado t ', 'valor de las unidades programadas a intervenir durante el trimestre de evaluación.'),
(18, 'Air-e.2.2.P', 'Cant. Mtto Real t ', 'cantidad de mantenimientos realizados sobre los activos del STR durante el semestre a evaluar, valor de las unidades constructivas instaladas en el trimestre t y acumulado según la curva S.'),
(19, 'Air-e.2.2.P', 'Cant Mtto Programado t', 'cantidad de mantenimientos programados durante el trimestre t, por activos en el STR registrados en el Módulo de Gestión de Consignaciones (MGC).'),
(20, 'Air-e.3.1.P', 'VUC_Ejecutado t', 'Valor de las unidades constructivas instaladas en el trimestre de evaluación.'),
(21, 'Air-e.3.1.P', 'VUC_Programado t', 'Valor de las unidades constructivas programadas a intervenir durante el trimestre de evaluación. '),
(22, 'Air-e.4.1.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa según curva S.'),
(23, 'Air-e.4.1.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa según curva S.'),
(24, 'Air-e.4.2.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(25, 'Air-e.4.2.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada.'),
(26, 'Air-e.4.3.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(27, 'Air-e.4.3.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada '),
(28, 'Air-e.4.4.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(29, 'Air-e.4.4.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada '),
(30, 'Air-e.4.5.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(31, 'Air-e.4.5.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada '),
(32, 'Air-e.4.6.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(33, 'Air-e.4.6.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada.'),
(34, 'Air-e.4.7.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(35, 'Air-e.4.7.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada.'),
(36, 'Air-e.4.8.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones de proyectos de instalación de medida centralizada.'),
(37, 'Air-e.4.8.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones proyectos de instalación de medida centralizada '),
(38, 'Air-e.5.1.P', '% Ejecución Programado', '% de Actividades Programadas según el cronograma del Plan de Gestión de Riesgo Eléctrico en el trimestre en evaluación.'),
(39, 'Air-e.5.1.P', '% Ejecución Real', '% de Actividades Ejecutadas según el cronograma de Plan del Gestión de Riesgo Eléctrico en el trimestre en evaluación.'),
(40, 'Air-e.6.1.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa'),
(41, 'Air-e.6.1.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa.'),
(42, 'Air-e.6.2.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa'),
(43, 'Air-e.6.2.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa.'),
(44, 'Air-e.7.1.P', '% Ejecución Programado', 'Porcentaje de actividades programadas en el cronograma presentado por el operador dentro del periodo de tiempo a evaluar.'),
(45, 'Air-e.7.1.P', '% Ejecución Real', 'Porcentaje de actividades ejecutadas dentro del cronograma presentado por el operador dentro del periodo de tiempo a evaluar.'),
(46, 'Air-e.7.2.P', '% Ejecución Programado', 'Porcentaje de actividades programadas en el cronograma presentado por el operador dentro del periodo de tiempo a evaluar.'),
(47, 'Air-e.7.2.P', '% Ejecución Real', 'Porcentaje de actividades ejecutadas dentro del cronograma presentado por el operador dentro del periodo de tiempo a evaluar.\n'),
(48, 'Air-e.8.1.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(49, 'Air-e.8.1.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa.\n'),
(50, 'Air-e.8.2.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(51, 'Air-e.8.2.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa.'),
(52, 'Air-e.1.1.a.R', 'SAIDIM_T', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones programadas y no programadas (META)'),
(53, 'Air-e.1.1.a.R', 'SAIDI_T', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones ocurridas programadas y no programadas'),
(54, 'Air-e.1.1.b.R', 'SAIDI_NP_M_T', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones no programadas (META)'),
(55, 'Air-e.1.1.b.R', 'SAIDI_NP_(T )', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones ocurridas no programadas.'),
(56, 'Air-e.1.2.a.R', 'SAIFIM_T', 'Frecuencia (cantidad total acumulada de los eventos) que perciben los usuarios en el SDL, incluye interrupciones programadas y no programadas (META).'),
(57, 'Air-e.1.2.a.R', 'SAIFI_T', 'Frecuencia (cantidad total acumulada de los eventos) que perciben los usuarios en el SDL, incluye interrupciones ocurridas programadas y no programadas.'),
(58, 'Air-e.1.2.b.R', 'SAIFI_NP_M_T', 'Frecuencia (cantidad total acumulada de los eventos) que perciben los usuarios en el SDL, incluye interrupciones no programadas (META).'),
(59, 'Air-e.1.2.b.R', 'SAIFI_NP_T', 'Frecuencia (cantidad total acumulada de los eventos) que perciben los usuarios en el SDL, incluye interrupciones ocurridas no programadas. '),
(60, 'Air-e.1.3.R', 'EventosProgramadosInformados', 'Interrupciones programadas informadas a los usuarios. '),
(61, 'Air-e.1.3.R', 'TotalEventosProgramados', 'Total de interrupciones programadas.'),
(62, 'Air-e.2.1.a.R', 'IA_NP_STR_t', 'Cantidad de horas de indisponibilidad de activos asociadas a interrupciones no programadas en activos del STR en el ańo t.'),
(63, 'Air-e.2.1.a.R', 'IA_NP_STRM_T', 'Meta de cantidad de horas de indisponibilidad de activos asociadas a interrupciones no programadas en activos del STR en el periodo T'),
(64, 'Air-e.2.1.b.R', 'IA_P_STR_t', 'Cantidad de horas de indisponibilidad de activos asociadas a interrupciones programadas en activos del STR en el ańo t.'),
(65, 'Air-e.2.1.b.R', 'IA_P_STRM_T', 'Meta de cantidad de horas de indisponibilidad de activos asociadas a interrupciones programadas en activos del STR en el periodo T.'),
(66, 'Air-e.3.1.R', 'TPts_con_medicion_t', 'Total puntos con medición instalados en el periodo evaluado t'),
(67, 'Air-e.3.1.R', 'TPts_Res024_t', 'Total puntos para cumplir con la senda resolución 024 del 2005 en el periodo evaluado t'),
(68, 'Air-e.3.2.R', 'R', 'número de registros en periodos de 10 minutos del universo de equipos tenidos en cuenta para el cálculo del indicador.'),
(69, 'Air-e.3.2.R', 'DET con medición R', 'Registro que presentó Desviación Estacionaria de Tensión en el periodo evaluado.'),
(70, 'Air-e.3.2.R', 'Registros con mediciónR ', 'sumatoria del total de los registros de todos los equipos que hacen parte del universo del cálculo del Indicador.'),
(71, 'Air-e.3.3.R', 'R', 'número de registros en periodos de 10 minutos del universo de equipos tenidos en cuenta para el cálculo del indicador.'),
(72, 'Air-e.3.3.R', 'THDV con_medicionR', 'Registro con distorsión en el periodo evaluado.'),
(73, 'Air-e.3.3.R', 'Registros con mediciónR ', 'sumatoria del total de los registros de todos los equipos que hacen parte del universo del cálculo del Indicador.'),
(74, 'Air-e.4.1.R', 'IPTs', 'Índice de pérdidas totales de la senda establecida según Resolución CREG 167 de 2020.'),
(75, 'Air-e.4.1.R', 'IPTp', 'Índice de pérdidas totales.'),
(76, 'Air-e.4.2.R', 'USMMt', 'Meta de cantidad de usuarios sin medidor'),
(77, 'Air-e.4.2.R', 'USMt ', 'Cantidad de usuarios sin medidor'),
(78, 'Air-e.5.1.R', 'N° AOEM_t', 'Numero de accidentes de Origen Eléctrico establecido como referencia para el periodo a evaluar dentro del PGLP.'),
(79, 'Air-e.5.1.R', 'N° AOE_t', 'Numero de accidentes de Origen Eléctrico reportados para el ańo a evaluar. '),
(80, 'Air-e.5.2.R', 'VUC_ejecutado t ', 'valor de las unidades constructivas instaladas durante cada uno de los trimestres de evaluación y acumulado en la curva S, valoradas según el listado de UC del capítulo 14 de la resolución CREG 015 de 2018.'),
(81, 'Air-e.5.2.R', 'VUC_programado t ', 'valor de las unidades programadas a intervenir durante cada uno de los trimestres a evaluar, valoradas según el listado de UC del capítulo 14 de la resolución CREG 015 de 2018.'),
(82, 'Air-e.6.1.R', '% NşSAPMT', 'Meta de número de Silencios Administrativos Positivos'),
(83, 'Air-e.6.1.R', '% NşSAPT', 'Silencios Administrativos Positivos en el periodo T.'),
(84, 'Air-e.6.2.R', 'RAP_Rev&Mod_t', 'Recursos de Apelación modificados y revocados en el periodo t'),
(85, 'Air-e.6.2.R', 'RAP_Rev&Mod_t', 'Recursos de Apelación modificados y revocados en el periodo t'),
(86, 'Air-e.6.2.R', 'RAP_(TOT_t )', 'Recursos de Apelación Totales en el periodo t'),
(87, 'Air-e.6.2.R', '%RAP_M', 'Porcentaje de RAPs meta para el periodo t'),
(88, 'Air-e.6.3.R', 'PQRnp_M ', 'PQR no presenciales meta para el periodo t'),
(89, 'Air-e.6.3.R', 'PQRnp_t', 'PQR no presenciales en el periodo t'),
(90, 'Air-e.7.1.R', '?_(Gi=1)^4EDP_Colaboradores_(Grupos_interes)   x 0', 'Resultado de las encuestas de sentido de pertenencia por parte de los colaboradores para el ańo evaluado.'),
(91, 'Air-e.7.1.R', 'EDPColaboradores_(ańo-1)', 'Resultado de las encuestas de sentido de pertenencia por parte de los colaboradores del ańo inmediatamente anterior al ańo evaluado.'),
(92, 'Air-e.7.2.R', '?_(Gi=1)^4 EDP_Usuarios_(Grupos_interes)   x 0.25', 'Resultado de las encuestas de imagen corporativa ante los usuarios del ańo evaluado.'),
(93, 'Air-e.7.2.R', 'EDP_Usuarios_(ańo-1)', 'Resultado de las encuestas de imagen corporativa ante los usuarios del ańo inmediatamente anterior al ańo evaluado.'),
(94, 'Air-e.8.1.R', 'CvPRONE_MMEt ', 'Número de convocatorias PRONE realizadas por el MME en el ańo t'),
(95, 'Air-e.8.1.R', 'CvPRONE_presenORt ', 'Número de convocatorias PRONE realizadas por el MME, a las cuales se presentó el operador durante el ańo t.'),
(96, 'Air-e.8.2.R', 'Total_PRONE_Terminadost ', 'Total proyectos PRONE culminados en el periodo.'),
(97, 'Air-e.8.2.R', 'Total_ PRONE_Prog_Termt', 'Total de proyectos que según cronograma se debieron terminar en el periodo. '),
(98, 'Air-e.8.3.R', 'CNBSNzt', 'Clientes Normalizados en Barrios Subnormales en el ańo t.'),
(99, 'Air-e.8.3.R', 'CNBSNMt', 'Clientes Normalizados en Barrios Subnormales según la Meta establecida para el ańo t. '),
(100, 'Air-e.8.4.R', 'IndiceMorosidadZDGt', 'Indice de Morosidad en Zonas de Difícil Gestión en el ańo de evaluación t.'),
(101, 'Air-e.8.4.R', 'MorosidadMt', 'Morosidad Meta establecida para el ańo t, de acuerdo con la senda de reducción acordada'),
(102, 'Air-e.9.1.R', 'No. Clientes Vinculados t', 'Número de clientes para los cuales se ha verificado y validado su vinculo cliente-transformador.'),
(103, 'Air-e.9.1.R', 'No. De Clientes Meta t', 'Número de clientes programado para realizar la verificación cliente-transformador en el periodo t'),
(104, 'Air-e.9.2.R', 'No. Fronteras Normalizadas s', 'Numero de fronteras normalizadas (registradas y aceptadas).'),
(105, 'Air-e.9.2.R', 'No. De Fronteras Meta s', 'Numero de fronteras programadas para normalizar en el periodo'),
(106, 'Afinia.1.1.P', '% Ejecución Programado', '% Inversión total programada hasta el trimestre que se evalúa'),
(107, 'Afinia.1.1.P', '% Ejecución Real', '% Inversión real ejecutada hasta el trimestre que se evalúa.'),
(108, 'Afinia.1.2.P', '% Ejecución Programado', '% Inversión total programada hasta el trimestre que se evalúa'),
(109, 'Afinia.1.2.P', '% Ejecución Real', '% Inversión real ejecutada hasta el trimestre que se evalúa'),
(110, 'Afinia.1.3.P', 'SAIDICMT', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones programadas y no programadas (META)'),
(111, 'Afinia.1.3.P', 'SAIDICT', 'Duración total en horas de los eventos que en promedio percibe cada usuario del circuito evaluado del SDL, incluye interrupciones ocurridas programadas y no programadas'),
(112, 'Afinia.1.4.P', 'SAIFICMT', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del circuito evaluado del SDL, incluye interrupciones programadas y no programadas (META).'),
(113, 'Afinia.1.4.P', 'SAIFICT', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del circuito evaluado del SDL, incluye interrupciones programadas y no programadas'),
(114, 'Afinia.1.5.P', 'Cantidad de eventos cerrados en XhT', 'cantidad de eventos atendidos con tiempo de duración entre 4 y 6 horas.'),
(115, 'Afinia.1.5.P', 'Cantidad total de eventos por Grupo evaluación T', 'Cantidad total de eventos en el periodo evaluado'),
(116, 'Afinia.1.6.a.P', 'Municipios interr_programadas', 'Municipios con interrupciones programadas. '),
(117, 'Afinia.1.6.a.P', 'Municipios con cobertura de comunicación por parte', 'Municipios con cobertura de comunicación por parte AFINIA'),
(118, 'Afinia.1.6.b.P', 'TotalUsuariosConMedio', 'Total usuarios cubiertos con medio de comunicaciones'),
(119, 'Afinia.1.6.b.P', 'UsuariosInfMedio', 'Total usuarios cubiertos con medio de comunicaciones    informados'),
(120, 'Afinia.2.1.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa.'),
(121, 'Afinia.2.1.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa.'),
(122, 'Afinia.2.2.P', '% Mantenimiento Programado', '% planeado para la ejecución del cronograma de actividades de mantenimiento.'),
(123, 'Afinia.2.2.P', '% Mantenimiento Real', '% ejecutado del cronograma de las actividades de mantenimiento'),
(124, 'Afinia.3.1.P', '% Ejecución Programado', '% Inversión total programada hasta el trimestre que se evalúa'),
(125, 'Afinia.3.1.P', '% Ejecución Real', '% Inversión real ejecutada hasta el trimestre que se evalúa'),
(126, 'Afinia.4.1.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa según curva S.'),
(127, 'Afinia.4.1.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa según curva '),
(128, 'Afinia.4.2.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones del plan de control de pérdidas.'),
(129, 'Afinia.4.2.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones del plan de control de pérdidas.'),
(130, 'Afinia.4.3.P', '% Ejecución Programado', '% de ejecución programado del cronograma de acciones del plan de reducción de pérdidas.'),
(131, 'Afinia.4.3.P', '% Ejecución Real', '% de ejecución real del cronograma de acciones del plan de reducción de pérdidas.'),
(132, 'Afinia.4.4.P', '% Ejecución Programado', '% planeado de ejecución del presupuesto aprobado en el plan de inversión para la gestión de pérdidas.'),
(133, 'Afinia.4.4.P', '% Ejecución Real', '% real ejecutado del presupuesto aprobado en el plan de inversión para la gestión de pérdidas.'),
(134, 'Afinia.5.1.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(135, 'Afinia.5.1.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa'),
(136, 'Afinia.6.1.P', '% Ejecución Programado', 'Inversión total programada hasta el trimestre que se evalúa'),
(137, 'Afinia.6.1.P', '% Ejecución Real', 'Inversión real ejecutada hasta el trimestre que se evalúa.'),
(138, 'Afinia.6.2.P', '% FRCt ', 'porcentaje de casos resueltos en el periodo t, mediante el programa de atención al cliente en primer contacto'),
(139, 'Afinia.6.2.P', '% FRCmt', 'porcentaje de casos resueltos Meta para el periodo t, mediante el programa de atención al cliente en primer contacto.'),
(140, 'Afinia.7.1.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(141, 'Afinia.7.1.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa'),
(142, 'Afinia.7.2.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(143, 'Afinia.7.2.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa'),
(144, 'Afinia.8.1.P', '% Ejecución Programado', '% Actividades programada en el trimestre que se evalúa.'),
(145, 'Afinia.8.1.P', '% Ejecución Real', '% Actividades ejecutadas en el trimestre que se evalúa'),
(146, 'Afinia.1.1.a.R', 'SAIDIMT', 'Duración total en horas de los eventos que en promedio percibe cada usuario del SDL, incluye interrupciones programadas y no programadas (META)'),
(147, 'Afinia.1.1.a.R', 'SAIDIT', 'Duración total en horas de los eventos que en promedio percibe cada usuario del SDL, incluye interrupciones ocurridas programadas y no programadas.'),
(148, 'Afinia.1.1.b.R', 'SAIDI_NP_MT', 'Duración total en horas de los eventos que en promedio percibe cada usuario del SDL, incluye interrupciones no programadas (META)'),
(149, 'Afinia.1.1.b.R', 'SAIDI_NPT  ', 'Duración total en horas de los eventos que en promedio percibe cada usuario del SDL, incluye interrupciones ocurridas no programadas'),
(150, 'Afinia.1.2.a.R', 'SAIFIMT', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del SDL, incluye interrupciones programadas y no programadas (META).'),
(151, 'Afinia.1.2.a.R', 'SAIFIT', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del SDL, incluye interrupciones ocurridas programadas y no programadas.  '),
(152, 'Afinia.1.2.b.R', 'SAIFI_NP_MT', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del SDL, incluye interrupciones no programadas (META)'),
(153, 'Afinia.1.2.b.R', 'SAIFI_NPT   ', 'Cantidad total de los eventos que en promedio perciben todos los usuarios del SDL, incluye interrupciones ocurridas no programadas.'),
(154, 'Afinia.1.3.R', 'EventosProgramadosInformados', 'Total de interrupciones programadas informadas                '),
(155, 'Afinia.1.3.R', 'TotalEventosProgramados', 'Total de interrupciones programadas'),
(156, 'Afinia.2.1.R', 'DNAt', 'Demanda no atendida durante el ańo t (MWh).'),
(157, 'Afinia.2.1.R', 'DNAMT', 'Meta de demanda no atendida para el ańo t (MWh).'),
(158, 'Afinia.2.1.a.R', 'IA_NP_STRt', 'Cantidad de horas de indisponibilidad de activos asociadas a interrupciones no programadas en activos del STR en el ańo t'),
(159, 'Afinia.2.1.a.R', 'IA_NP_STRM_t', 'Meta de cantidad de horas de indisponibilidad de activos asociadas a interrupciones no programadas en activos del STR en el periodo T'),
(160, 'Afinia.2.1.b.R', 'IA_P_STRt', 'Cantidad de horas de indisponibilidad de activos asociadas a interrupciones programadas en activos del STR en el ańo t.'),
(161, 'Afinia.2.1.b.R', 'IA_P_STRMT', 'Meta de cantidad de horas de indisponibilidad de activos asociadas a interrupciones programadas en activos del STR en el periodo T.'),
(162, 'Afinia.3.1.R', 'TPts_con_medicion ejecutadost', 'Total de puntos de medición que se les instaló equipo de calidad de la potencia en el periodo t'),
(163, 'Afinia.3.1.R', 'TPts_con_medición_Viables', 'Total de puntos de medición viables para la instalación de equipos de calidad de la potencia'),
(164, 'Afinia.3.2.a.R', 'T_(sem ańo)', 'Semanas del ańo'),
(165, 'Afinia.3.2.a.R', 'DETs_(con medición t)', 'Total de Semanas con registros de desviación de tensión en estado estacionario de los puntos del sistema con medición los cuales cumplen con los rangos definidos en la regulación.'),
(166, 'Afinia.3.2.a.R', 'Registro_BC', 'Total de registros de los puntos del sistema con medición'),
(167, 'Afinia.3.2.b.R', 'T_(sem ańo)', 'Semanas del ańo'),
(168, 'Afinia.3.2.b.R', 'ITs_(con medición t)', 'Total de semanas con registros de interrupciones transitorias de los puntos del sistema con medición los cuales cumplen con los rangos definidos en la regulación.'),
(169, 'Afinia.3.2.b.R', 'Registro_BC', 'Total de registros de los puntos del sistema con medición'),
(170, 'Afinia.3.3.R', 'T_(sem ańo)', 'Semanas del ańo'),
(171, 'Afinia.3.3.R', 'PERC_95registros_cumple', 'Total de registros que cumplen con los rangos definidos en la regulación para la variable THDV'),
(172, 'Afinia.3.3.R', 'Tmed', 'Total de puntos con medición'),
(173, 'Afinia.4.1.R', 'IPTs', 'Índice de pérdidas totales de la senda establecida según Resolución CREG 167 de 2020.'),
(174, 'Afinia.4.1.R', 'IPTp', 'Índice de pérdidas totales'),
(175, 'Afinia.4.2.R', '%PartMT', 'Meta para la participación de clientes sin medidor respecto de clientes totales, para el periodo T'),
(176, 'Afinia.4.2.R', 'CSMEdT', 'Clientes sin medidor en el periodo T'),
(177, 'Afinia.4.2.R', 'Total ClientesT', 'Total clientes en el periodo T'),
(178, 'Afinia.5.1.R', 'No AOEMt ', 'Número de Accidentes de Origen Eléctrico Meta para el periodo t (2020).'),
(179, 'Afinia.5.1.R', 'No AOEt', 'Número de Accidentes de Origen Eléctrico Total ańo t'),
(180, 'Afinia.5.2.R', '%Ejecución Programado', 'Porcentaje de ejecución del proyecto programado y definido en el cronograma y curva S.'),
(181, 'Afinia.5.2.R', '%Ejecución Real', 'Porcentaje de ejecución real del proyecto en el periodo t'),
(182, 'Afinia.6.1.R', '% NşSAPMT', 'Meta de número de Silencios Administrativos Positivos'),
(183, 'Afinia.6.1.R', '% NşSAPT', 'Silencios Administrativos Positivos en el periodo T.'),
(184, 'Afinia.6.2.R', 'RAP_Rev&Mod_t', 'Recursos de Apelación modificados y revocados en el periodo t'),
(185, 'Afinia.6.2.R', 'RAP_(TOT_t )', 'Recursos de Apelación Totales en el periodo t'),
(186, 'Afinia.6.2.R', '%RAP_M', 'Porcentaje de RAPs meta para el periodo t'),
(187, 'Afinia.7.1.R', 'Calificación SPCt ', 'Calificación del Sentido de Pertenencia de los colaboradores en el ańo de evaluación.'),
(188, 'Afinia.7.1.R', 'Calificación SPCt-1', 'Calificación del Sentido de Pertenencia de los colaboradores en el ańo anterior al ańo de evaluación.'),
(189, 'Afinia.7.2.R', 'Calificación SPCt', 'Calificación del Sentido de Pertenencia de los usuarios en el ańo de evaluación t.'),
(190, 'Afinia.7.2.R', 'Calificación SPCt-1', 'Calificación del Sentido de Pertenencia de los colaboradores en el ańo t-1.'),
(191, 'Afinia.8.1.R', 'CNBSNt ', 'Clientes normalizados en barrios subnormales para el ańo t'),
(192, 'Afinia.8.1.R', 'CNBSNMt ', 'Clientes normalizados en barrios subnormales Meta para el ańo t.\n'),
(193, 'Afinia.8.2.R', 'CMed_Prepagot', 'Cantidad de clientes con sistema de medición prepago instalado para el ańo t.'),
(194, 'Afinia.8.2.R', 'CObjetivo _Prepagot', 'Mercado Objetivo para la instalación de medición prepago.'),
(195, 'Afinia.8.2.R', 'CPMOMt', 'Cantidad de clientes con sistema de medición prepago meta, definido en la senda para el ańo t'),
(196, 'Afinia.8.3.R', 'Cartera vencida mayor a 60 días', 'Valor en pesos de la cartera vencida mayor a 60 días en el total del mercado del operador.'),
(197, 'Afinia.8.3.R', 'Total de la Cartera', 'Valor en pesos del Total de la Cartera existente en el mercado del operador, en el ańo de evaluación.');